### ISSUE TITLE
Выделение IP на основе CIDR а не Subnet ID

### ISSUE THREAD

**Issue by akrush24** [akrush24/vmware-automation#1]
Пример реализации 

$ curl -H 'token:6Bbjz4WsQ68DsM5U!506MO--' http://ipam.phoenixit.ru/api/apiclient/subnets/cidr/192.168.24.0/24 

{"code":200,"success":true,"data":[{"id":"22","subnet":"192.168.24.0","mask":"24","sectionId":"3","description":null,"linked_subnet":null,"firewallAddressObject":null,"vrfId":"0","masterSubnetId":"16","allowRequests":"0","vlanId":"70","showName":"0","device":"0","permissions":"[]","pingSubnet":"1","discoverSubnet":"1","DNSrecursive":"0","DNSrecords":"0","nameserverId":"0","scanAgent":"1","isFolder":"0","isFull":"0","tag":"2","threshold":"0","location":"0","editDate":"2018-08-24 13:45:01","lastScan":"2018-08-24 13:45:01","lastDiscovery":"2018-08-24 13:45:01","resolveDNS":"0"},{"id":"130","subnet":"192.168.24.0","mask":"24","sectionId":"21","description":null,"linked_subnet":null,"firewallAddressObject":null,"vrfId":"0","masterSubnetId":"141","allowRequests":null,"vlanId":"0","showName":"0","device":"0","permissions":"[]","pingSubnet":"1","discoverSubnet":"1","DNSrecursive":"0","DNSrecords":"0","nameserverId":"0","scanAgent":"2","isFolder":"0","isFull":"0","tag":"2","threshold":"0","location":"12","editDate":"2018-08-15 11:31:58","lastScan":null,"lastDiscovery":null,"resolveDNS":"0"}],"time":0.01}[

**Comment by nikolonso** [comment]
ready
